services:
  coturn:
    image: coturn/coturn:latest
    container_name: turn_server
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-49251:49152-49251/udp"
    env_file: .env
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    command: 
      - turnserver
      - -c /etc/coturn/turnserver.conf
      - --user=${TURN_USER}:${TURN_PASS}
      - --realm=${TURN_REALM}
      - --external-ip=${SERVER_IP}