# Default listening port
listening-port=3478

# Relay ports
min-port=50000
max-port=51000

# Authentication & Session rules
fingerprint
lt-cred-mech

# Allowing loopback connection
allow-loopback-peers

# Logging
log-file=stdout